# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b40e63d2741fc71ce6c1088be67e8af94e4ca98a4dfec4db60be2915b7f4f99dc7825dcf49236603c06adc2fd31fb39c49c4985a85526e9ee6fd067bc9137f0

test:
  secret_key_base: 73d44a0cd7e722d755b0faf653b47ad473f7154b83e4e16c9f19974f85438f5b314882a630159025ca39e05b8e80168584a9f84d6b232c561dfb17b0e75cedbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
